name: Trigger auto deployment for mcp-server-try-clang

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mcp-server-try-clang-AutoDeployTrigger-38adcff0-9ef3-4b36-9974-cff53c0987d9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MCPSERVERTRYCLANG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MCPSERVERTRYCLANG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MCPSERVERTRYCLANG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.MCPSERVERTRYCLANG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MCPSERVERTRYCLANG_REGISTRY_PASSWORD }}
          containerAppName: mcp-server-try-clang
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


